python3 called.py --reg gpFULL3 --stepSize 2 --lastKDays 5 --datafile ../../data/beijingb_scaled.csv --loc results -s
python3 called.py --reg gpFULL3 --stepSize 2 --lastKDays 6 --datafile ../../data/beijingb_scaled.csv --loc results -s
python3 called.py --reg gpFULL3 --stepSize 2 --lastKDays 7 --datafile ../../data/beijingb_scaled.csv --loc results -s
python3 called.py --reg gpFULL3 --stepSize 2 --lastKDays 8 --datafile ../../data/beijingb_scaled.csv --loc results -s
python3 called.py --reg gpFULL3 --stepSize 2 --lastKDays 9 --datafile ../../data/beijingb_scaled.csv --loc results -s
python3 called.py --reg gpFULL4 --stepSize 2 --lastKDays 2 --datafile ../../data/beijingb_scaled.csv --loc results -s
python3 called.py --reg gpFULL4 --stepSize 2 --lastKDays 3 --datafile ../../data/beijingb_scaled.csv --loc results -s
python3 called.py --reg gpFULL4 --stepSize 2 --lastKDays 4 --datafile ../../data/beijingb_scaled.csv --loc results -s
python3 called.py --reg gpFULL4 --stepSize 2 --lastKDays 5 --datafile ../../data/beijingb_scaled.csv --loc results -s
