python3 called.py --reg gpST2 --stepSize 2 --lastKDays 6 --datafile ../../data/beijinga_scaled.csv --loc results -s
python3 called.py --reg gpST2 --stepSize 2 --lastKDays 7 --datafile ../../data/beijinga_scaled.csv --loc results -s
python3 called.py --reg gpST2 --stepSize 2 --lastKDays 8 --datafile ../../data/beijinga_scaled.csv --loc results -s
python3 called.py --reg gpST2 --stepSize 2 --lastKDays 9 --datafile ../../data/beijinga_scaled.csv --loc results -s
python3 called.py --reg gpST3 --stepSize 2 --lastKDays 2 --datafile ../../data/beijinga_scaled.csv --loc results -s
python3 called.py --reg gpST3 --stepSize 2 --lastKDays 3 --datafile ../../data/beijinga_scaled.csv --loc results -s
python3 called.py --reg gpST3 --stepSize 2 --lastKDays 4 --datafile ../../data/beijinga_scaled.csv --loc results -s
python3 called.py --reg gpST3 --stepSize 2 --lastKDays 5 --datafile ../../data/beijinga_scaled.csv --loc results -s
python3 called.py --reg gpST3 --stepSize 2 --lastKDays 6 --datafile ../../data/beijinga_scaled.csv --loc results -s
